/*
 * otpfwvar.h - REAL DESTINATION: sys/net/otpfwvar.h in your OpenBSD
 * kernel source tree (see ../README.md's "Kernel integration").
 *
 * The public interface otpfw.c exposes to the four patched call sites in
 * ip_output.c/ip_input.c/ip6_output.c/ip6_input.c - deliberately just two
 * functions, the same "one call, all real logic lives elsewhere" shape
 * pf(4) itself has at those exact call sites (pf_test()/pf_test6()).
 * otpfw_hook_out()/otpfw_hook_in() each auto-detect IPv4 vs IPv6 from the
 * packet's own IP version nibble, so the SAME function is called from
 * both the v4 and v6 call site for a given direction - only 2 kernel
 * functions, patched into 4 places.
 *
 * `#if NOTPFW > 0` follows the exact same pattern `#if NPF > 0` uses
 * around pf_test()/pf_test6() calls: NOTPFW is generated by config(8)
 * from the `pseudo-device otpfw` line in your kernel config (see
 * ../README.md's "Kernel integration" step 4 - `OTPFW` there, or
 * whatever you name your own copy of `GENERIC`) into an auto-generated
 * otpfw.h - a kernel built WITHOUT that line compiles these call sites
 * out entirely, to nothing, the same
 * "not compiled in at all" state module-based platforms get by simply
 * not loading their .ko. See ../README.md's "Activate" section for
 * the second, independent runtime on/off switch (the /dev/otpfw kill
 * switch), which is what `otpfwctl enable/disable` actually uses day to
 * day - NOTPFW is a build-time choice you only revisit by rebuilding and
 * rebooting into a different kernel.
 *
 * UNVERIFIED - see ../README.md's Status section.
 */

#ifndef _NET_OTPFWVAR_H_
#define _NET_OTPFWVAR_H_

#include "otpfw.h" /* config(8)-generated: defines NOTPFW */

#if NOTPFW > 0

struct mbuf;
struct ifnet;

/* Called from ip_output()/ip6_output(), immediately next to the
 * existing pf_test()/pf_test6() call - see ../README.md's "Kernel
 * integration" for exactly where. Returns 1 if the hook consumed *mp
 * (either queued it for an async verdict from otp_firewalld, or dropped
 * it outright itself - no configured contact for this address, not
 * TCP/UDP, oversized, or an allocation failure) - the caller must treat
 * this exactly like a pf_test() DROP verdict: stop processing this
 * packet the same way the neighboring pf_test() failure branch already
 * does, and never touch *mp again (it's already been freed or handed
 * off). Returns 0 if *mp is completely unchanged and the caller should
 * fall through to its normal processing - true when
 * the kill switch is off (fail-open passthrough), for the ICMPv6
 * Neighbor Discovery and delivery-ack-port exemptions (see
 * ../../README.md), and for this hook's own reinjected packet passing
 * through a second time (see otpfw.c's OTPFW_MTAG_REINJECTED mbuf-tag
 * loop-avoidance note). */
int otpfw_hook_out(struct mbuf **mp, struct ifnet *ifp);

/* Same contract as otpfw_hook_out(), called from ip_input()/ip6_input()
 * next to pf_test()/pf_test6() there. */
int otpfw_hook_in(struct mbuf **mp, struct ifnet *ifp);

#define OTPFW_HOOK_OUT(mp, ifp) otpfw_hook_out((mp), (ifp))
#define OTPFW_HOOK_IN(mp, ifp) otpfw_hook_in((mp), (ifp))

#else /* !NOTPFW */

/* Kernel built without `pseudo-device otpfw` in its config: the call
 * sites compile to nothing at all, not even a function call - same
 * "doesn't exist" state as pf's own call sites when NPF == 0. */
#define OTPFW_HOOK_OUT(mp, ifp) 0
#define OTPFW_HOOK_IN(mp, ifp) 0

#endif /* NOTPFW */

#endif /* _NET_OTPFWVAR_H_ */
